name: sqwa
description: A new Flutter project.

dependencies:
  
  flutter:
    sdk: flutter
  firebase_auth: ^0.6.2+1
  firebase_analytics: ^1.0.4
  image_picker: ^0.4.10
  firebase_database: ^2.0.2
  firebase_storage: ^2.1.0+1
  intl: ^0.15.7
  url_launcher: ^4.0.3
  cloud_firestore: ^0.9.7
  rxdart: ^0.21.0
  
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.6.1

flutter_icons:
  android: false 
  ios: true
  image_path: "assets/ios/AppIcon.png"
  
  


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/owl.png
  - assets/logo.jpg
  - assets/default_profile_pic.jpg
  - assets/beach.jpg
  - assets/beach2.jpg
  - assets/soccer.jpg
  - assets/wonderland.jpg
  - assets/drinks.jpg
  - assets/basketball.jpg
  - assets/travel.jpg
  - assets/sushi.jpg
  - assets/coffee.jpg
  - assets/red.png
  - assets/blue.png
  - assets/whiteish.png
  - assets/setup/login_red.png
  - assets/owl_red.png
  - assets/group.png
  - assets/suggestions/adventure.png
  - assets/suggestions/chill_drinks.png
  - assets/suggestions/coffee.png
  - assets/suggestions/food.png
  - assets/suggestions/hang.png
  - assets/suggestions/lit.png
  - assets/suggestions/pickup.png
  - assets/suggestions/trip.png
  - assets/suggestions/wonderlandPurple.png
  - assets/suggestions/drinks.png
  - assets/suggestions/gymBuddy.png
  - assets/ios/AppIcon.png
  


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

    - family: PlayList
      fonts:
        - asset: assets/Playlist-Caps.ttf
        - asset: assets/Playlist-Ornament.ttf
        - asset: assets/Playlist-Script.ttf 
    - family: SF
      fonts: 
         - asset: assets/ios/SF-Pro-Display-Bold.otf
         - asset: assets/ios/SF-Pro-Display-Regular.otf
         - asset: assets/ios/SF-Pro-Text-Bold.otf
         - asset: assets/ios/SF-Pro-Text-Regular.otf
    - family: Julius
      fonts:
         #- asset: assets/Cairo-ExtraLight.ttf
         - asset: assets/JuliusSansOne-Regular.ttf
    - family: gotham_bold
      fonts:
        - asset: assets/fonts/gotham_bold.otf
    - family: gotham_normal
      fonts:
        - asset: assets/fonts/gotham_normal.otf

    - family: gotham_medium
      fonts:
        - asset: assets/fonts/gotham_medium.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
